version: '3.5'

services:
  db_address_service:
    container_name: db_address_service
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:15.3-alpine3.18